name: Lesley Jesseau
favicon: null
layout_spectrum: 0.2409
typography_spectrum: 0.6063277693465352
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.3125
  lightness: 1
  saturation: 1
  rhythmicContrast: 0
purpose: []
